### ISSUE TITLE
[Request] Keep original filename

### ISSUE THREAD

**Issue by blinkydoos** [eklipse2009/ZX-Pokemaster#1]
Hi, this program is excellent, very impressive. Can I request an option to keep my original filenames and add tags to the end ? I ask this because my collection has matching in-game screenshots and if I rename the Spectrum games with Pokemaster then they appear vastly different to the screenshot names and would probably have to manually edit most of them to match. Maybe two possibilities -

1) An option to add a screenshots directory that are named the same as the Spectrum games, then when Pokemaster renames the game/poke it will also rename the screenshot the same.

2) An option to use the current filename and add any extra tags, for example, currently if my files are named as follows -

After the War (1989) (Dinamic Software) (Part 1).tap
After the War (1989) (Dinamic Software) (Part 2).tap
Agent-X II (1987) (Mastertronic) (Part 1).tzx
Agent-X II (1987) (Mastertronic) (Part 2).tzx
Agent-X II (1987) (Mastertronic) (Part 3).tzx
Little Computer People (1986) (Activision).tzx

Pokemaster renames them to -

Activision Little Computer People Discovery Kit, The (1987) (Activision) [128K].tzx (??? This is an alternate name)
After the War (1989) (Dinamic) [48K] (Tape 2 of 2).tap
After the War (1989) (Dinamic) [48K].tap
Agent X II - The Mad Prof's Back! (1987) (Mastertronic) [48K-128K] (Tape 1 of 3).tzx
Agent X II - The Mad Prof's Back! (1987) (Mastertronic) [48K-128K] (Tape 2 of 3).tzx
Agent X II - The Mad Prof's Back! (1987) (Mastertronic) [48K-128K] (Tape 3 of 3).tzx

So what I would like is a pattern like -

{Original File Name} [{MachineType}]

Which would give me -

Little Computer People (1986) (Activision) [128K].tzx
etc.

**Comment by eklipse2009** [comment]
Yes, this is easy!
Many thanks for the feedback!
I'll get back to you when this option is ready.

**Comment by eklipse2009** [comment]
About alternate titles.
The current algorythm is this:
If the alternate title fully contains the main title, use alternate title as the game name.
Thus, if we have "Saboteur II" as a title and "Saboteur II - Avenging Angel" as an alternative title, the latter is preferred,  because it contains more information about the game.
As for the game you mentioned, the full title is written on the cassette inlay:
http://spectrumcomputing.co.uk/pub/sinclair/games-inlays/l/LittleComputerPeople.jpg
This is a topic for a debate and you're welcome to introduce your arguments.

**Comment by blinkydoos** [comment]
Thanks for the info, I wasn't expecting you to reply so quickly !

The screenshots I mostly got from WOS and converted them to .png, and made a few myself. I mostly use my collection in a Raspberry Pi and Android so my in-game images are named exactly the same as the Spectrum game.

So if all my images are in for example an 'images' folder (currently named the same as the games) and the folder is selected in Pokemaster, when it renames the games it will also rename the image the same.

images/Chase H.Q. (1989) (Ocean).png
Chase H.Q. (1989) (Ocean).tzx

would become

images/Chase H.Q. (1989) (Ocean) [48K-128K].tzx
POKES/Chase H.Q. (1989) (Ocean) [48K-128K].tzx
Chase H.Q. (1989) (Ocean) [48K-128K].tzx

This feature will probably only be useful to me ! unless other people need to rename their images and games to the Pokemaster TOSEC name etc.

I completely agree with the alternate names now, I never realised that was the full name to 'Little Computer People'.

**Comment by eklipse2009** [comment]
Thank you for the follow-up.
The issue with screenshots is a bit complicated.
I've already mentioned that there are a lot of options how to names them. Currently it's not possible to determine which screenshot is which, if no MD5 is stored and there is more than 1 screenshot per game and it's not known under which name and in which folder they're stored. This would increase code complexity beyond need.
Here is what I'm about to do.
I collect infromation about all screenshots and loading screens stored in GIF and SCR formats from WoS FTP mirrors. 
ZX Pokemaster will correctly determine all the screenshots and rename them the same way the .POK files are named.
If necessary, you may convert all SCR and GIF files to PNG yourself, but if the time allows, I can implement this conversion in ZX Pokemaster as well.
Be advised though that it will take a while, because it's far on my priority list.

About alternate names, I've started a debate in TOSEC chat and asked Einar Saukas, the author of ZXDB, about his opinion. So my policy regarding that may change.

Best regards,
Helga.

**Comment by blinkydoos** [comment]
Is there any chance of a quick fix for locally stored images (like my case) ? I already have all the images in a folder. Maybe if Pokemaster knows what folder to look in and the image filename matches the game name exactly (minus the extension) then it will also be renamed ?

**Comment by eklipse2009** [comment]
OK, here's what we'll do:
I'll make an option to "Include supplementary files".
If checked, ZX Pokemaster will look for files with other extensions but the same file name in the same folder or up to one level in subfolders.
Then all images, pokes, rzx videos, screenshots - will be imported alongside with the files, while renamed accordingly. 
This is the quickest and easiest it can be, but it is not a 5-minutes work, so please have patience.
Will this satisfy your needs?

**Comment by blinkydoos** [comment]
Perfect, thanks for your hard work.

**Comment by eklipse2009** [comment]
I've done what you asked and uploaded a new beta version for you.
Could you please test it out and report whether it satisfies your requirements?
https://sourceforge.net/projects/zx-pokemaster/files/ZXPokemaster_win32_1.2-beta4.zip/download

**Comment by eklipse2009** [comment]
Forgot to add:
Please check "Include supplementary files" on "File filtering" tab. It is unchecked by default.

**Comment by blinkydoos** [comment]
OK, I gave it a little test. I'll keep adding to this post because I keep forgetting what I tested !

I tried {GameName} {MachineType} but it missed out renaming 10 images. I checked the missing images and they are named exactly the same as the game so I'm not sure why this happened.

**Comment by eklipse2009** [comment]
Thanks for the test!
Perhaps these images are not added to the database yet!
I'll be grateful if you could share these images with me.
Since I'm part of TOSEC team, I'll add them to TOSEC as well.

**Comment by blinkydoos** [comment]
When I say images I mean my pictures.

**Comment by eklipse2009** [comment]
Could you please share the pictures along with the executables they're meant to represent?

**Comment by blinkydoos** [comment]
OK, I'll just run it one more time to double check.

**Comment by blinkydoos** [comment]
My mistake, sorry. I had multiple versions with the same game name and forgot to add the {Publisher} tag.

**Comment by blinkydoos** [comment]
If the 'include supplementary files' option is on, would 'Traverse subdirectories' conflict in any way ?

**Comment by eklipse2009** [comment]
No, it shouldn't.
By "supplementary files" I meant files with the same name as an executable file, but an extension not zip, not zx spectrum executable and not .pok.

**Comment by blinkydoos** [comment]
Thanks, I'll close this for now.
